baseurl = "https://shapeshed.com/"
languageCode = "en-gb"
theme = "shapeshed-minimal"
title = "George Ornbo"
RSSUri = "atom.xml"
copyright = "Shape Shed"
metaDataFormat = "json"
paginate = "3"
sitemap = "sitemap.xml"
googleAnalytics= "UA-324369-3"
[permalinks]
  post= "/:slug/"
[params]
  author = "George Ornbo"
  description = "Articles by George Ornbo, a London-based technologist"
  GoogleAnalytics= "UA-324369-3"
