baseurl = "http://shapeshed.com/"
languageCode = "en-gb"
theme = "shapeshed-minimal"
title = "Shape Shed"
RSSUri = "atom.xml"
copyright = "Shape Shed"
metaDataFormat = "json"
paginate = "3"
sitemap = "sitemap.xml"
[permalinks]
  post= "/:slug/"
[params]
  author = "George Ornbo"
  description = "Articles by George Ornbo, a London-based technologist"
  GoogleAnalytics= "UA-324369-3"
